### ISSUE TITLE
Is this reliable for production?

### ISSUE THREAD

**Issue by himanshub16** [iddogino/mongoTriggers#4]
Thanks for contributing your work to the community.
I was developing an application which requires event-triggers on a Mongo Database.

I had few queries:
* Do you recommend this library for production? You might be well aware of its performance and reliability.
* The page on NPM mentions this is *MIT Licensed*, but you haven't mentioned the license on this repo.

**Comment by xeewi** [comment]
Same questions ! :+1:

**Comment by iddogino** [comment]
Hey @himanshub16 and @xeewi, to answer your questions:

- *Production use*: I'm currently using it in a "production" side-app with ~100,000 monthly active users. It works pretty smoothly. As you can see I haven't updated it, but it 'just works' for now. The code base itself is pretty small (can probably read & fully understand in 15 mins), so worst case scenario you can probably refactor yourself as needed (VS huge open source projects it'd take you months to comprehend). Performance is pretty decent - it depends on the triggered function, but overhead is insignificant.
-  *License*: MIT indeed.

**Comment by himanshub16** [comment]
Thanks @iddogino ! 👍
