### ISSUE TITLE
mongodb

### ISSUE THREAD

**Issue by YunusEmrahDursun** [iddogino/mongoTriggers#5]
Is there a way with use mongodb nodejs native driver ? 
when i use  `triggers(db.collection("test")).on('insert'.....`
its not triggered. But "mongojs" works well.

**Comment by DeliDoktoru** [comment]
> Is there a way with use "mongodb" ?
> when i use `triggers(db.collection("test")).on('insert'.....`
> its not triggered. But "mongojs" works well.

**Comment by YunusEmrahDursun** [comment]
i solved, if anyone need;
`collection.insert = injectTriggers(collection.insert, triggers.insert, listeners.insert); `
to
` collection.__proto__.insert = injectTriggers(collection.insert, triggers.insert, listeners.insert);`
